version: '3'

services:
  app:
    build: './src/app'
    volumes:
      - './src/app:/app'
    ports:
      - '80:80'

  github-release:
    image: 'github-release'
    build: './src'

  docker-push:
    image: 'tmvdl/projects:python'
    build: './src/app'
