version: '3'

services:
  http:
    build: './src/http'
    volumes:
      - './src/http:/http'
    ports:
      - '80:80'

  github-release:
    image: 'github-release'
    build: './src'

  docker-push:
    image: 'tmvdl/projects:python'
    build: './src/http'
