name: Docker pull

on:
  workflow_dispatch:
  schedule:
    - cron: '50 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull
        run: docker push tmvdl/projects -a
